name: CI Server

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    run:
      shell: bash
      working-directory: ./server
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Check code formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        run: staticcheck ./...
